### ISSUE TITLE
background is not working

### ISSUE THREAD

**Issue by PeopleRights** [PeopleRights/PeopleRights.github.io#1]
Anyone know how to fix?

**Comment by imdevarsh** [comment]
Wait, so, organisations can open issues!?!?!??

The background should work now

**Comment by Chiroyce1** [comment]
@derter-menter i have some suggestions

(1) Make new issues for ones that you want help with, feel free to ping me and i'll take a look at it if i have time
(2) try to make your commit messages make more sense, the default ones are not descriptive at all.
<img width="133" alt="image" src="https://user-images.githubusercontent.com/97374054/160224523-65d565f0-d3b6-4471-9434-ef32966ef5c9.png">
